baseURL: "https://blog.crazykids.tech" # 绑定的域名
languageCode: "zh" # en-us
title: "我的碎碎念"
theme: "PaperMod" # 主题名字，和themes文件夹下的一致

enableInlineShortcodes: true
enableEmoji: true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT: true # 允许爬虫抓取到搜索引擎，建议 true
hasCJKLanguage: true # 自动检测是否包含 中文日文韩文 如果文章中使用了很多中文引号的话可以开启

buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45 # 谷歌统计

paginate: 15 # 首页每页显示的文章数
summaryLength: 140 # 文章概览的自字数，默认70

minify:
  disableXML: true

permalinks: # 访问博客时网址的显示形式
  post: "/:title/"

defaultContentLanguage: "zh" # 最顶部首先展示的语言页面
defaultContentLanguageInSubdir: true

languages:
  zh:
    languageName: 中文
    languageCode: zh
    contentDir: content/Chinese
    menu:
      main:
        - weight: 1
          identifier: "post"
          name: "文章"
          url: "/zh/posts/"
        - weight: 2
          identifier: "tags"
          name: "标签"
          url: "/zh/tags/"
        - weight: 3
          identifier: "categories"
          name: "分类"
          url: "/categories/"
        - weight: 4
          identifier: "memora"
          name: "Memora"
          url: "https://www.memora.top"
        - weight: 5
          identifier: "twitterxvidoe"
          name: "TwitterXVideo"
          url: "https://twittervideoindir.com"
        - weight: 9
          identifier: "about"
          name: "关于"
          url: "/zh/about/"
        - weight: 10
          identifier: "search"
          name: "搜索"
          url: "/zh/search/"
  en:
    languageName: English
    languageCode: en
    contentDir: content/English
    menu:
      main:
        - weight: 1
          identifier: "post"
          name: "Posts"
          url: "/en/posts/"
        - weight: 2
          identifier: "tags"
          name: "Tags"
          url: "/en/tags/"
        # - weight: 3
        #   identifier: 'categories'
        #   name: '分类'
        #   url: '/categories/'
        - weight: 4
          identifier: "memora"
          name: "Memora"
          url: "https://www.memora.top"
        - weight: 5
          identifier: "twitterxvidoe"
          name: "TwitterXVideo"
          url: "https://twittervideoindir.com"
        - weight: 9
          identifier: "about"
          name: "About"
          url: "/en/about/"
        - weight: 10
          identifier: "search"
          name: "Search"
          url: "/en/search/"
outputs:
  home:
    - HTML
    - RSS
    - JSON

# 这里的参数会被代码以 .Site.Params 的形式读取
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: ""
  author: duanhongjin

  defaultTheme: auto # defaultTheme: light or  dark
  disableThemeToggle: false
  DateFormat: "2006-01-02"
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecialistPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideFooter: false # 隐藏页脚
  ShowWordCounts: true
  VisitCount: true
  ShowLastMod: true #显示文章更新时间

  ShowToc: true # 显示目录
  TocOpen: true # 自动展开目录

  extendCodeBackground: false # 代码块是否自动横向展开

  comments: true

  profileMode:
    enabled: false
    title: "我的碎碎念"

  socialIcons:
    - name: github
      url: "https://github.com/duan0120"
    - name: x
      url: "https://x.com/duanhjlt"
    - name: telegram
      url: "https://t.me/duanhjlt"
    - name: email
      url: "mailto:duanhjlt@gmail.com"

  # label: # 左上角图标
  #   text: "TimeStamps"
  #   # icon: "img/Q.gif"
  #   # iconHeight: 35

  analytics:
    google:
      SiteVerificationTag: ""

  # assets:
  #   favicon: "img/Q.gif"
  #   favicon16x16: "img/Q.gif"
  #   favicon32x32: "img/Q.gif"
  #   apple_touch_icon: "img/Q.gif"
  #   safari_pinned_tab: "img/Q.gif"
  #   disableFingerprinting: true # 禁用指纹

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  fuseOpts: # 搜索配置
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary"]

  StartYear: 2020 # 底部开始年份
  # FilingNo: 填写自己的备案号 # 底部备案号
  # PublicSecurityIconLink: 填自己的公安图标链接 # 填自己的公安图标链接,可用绝对路径，相对路径如 img/beian.png
  # PublicNetworkSecurity: 填自己的公网安备 # 底部公网安备号

  Reward: true #打赏是否开启
  # 打赏微信图片地址，
  # 可用绝对和相对地址，相对地址的图片需放在static/img下，
  # 填写格式为img/wechat_pay.png
  # WechatPay: img/wechat_pay.png
  # Alipay: img/alipay.png #打赏支付宝图片地址

  # twikoo评论
  # twikoo:
  #   version: 1.5.8 # 填写twikoo版本号
  #   id:  # 填写自己的twikoo id
  #   region:  # 环境地域，默认为 ap-shanghai，如果您的环境地域不是上海，需传此参数，请看twikoo官方文档

  editPost:
    URL: "https://github.com/duanhjlt/blog/tree/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

taxonomies:
  category: "categories"
  tag: "tags"
  series: "series"

markup:
  goldmark:
    renderer:
      unsafe: true # HUGO 默认转义 Markdown 文件中的 HTML 代码，如需开启的话
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: true
    noClasses: true
    tabWidth: 4
    style: monokai
    # codeFences：代码围栏功能，这个功能一般都要设为 true 的，不然很难看，就是干巴巴的-代码文字，没有颜色。
    # guessSyntax：猜测语法，这个功能建议设置为 true, 如果你没有设置要显示的语言则会自动匹配。
    # hl_Lines：高亮的行号，一般这个不设置，因为每个代码块我们可能希望让高亮的地方不一样。
    # lineNoStart：行号从编号几开始，一般从 1 开始。
    # lineNos：是否显示行号，我比较喜欢显示，所以我设置的为 true.
    # lineNumbersInTable：使用表来格式化行号和代码,而不是 标签。这个属性一般设置为 true.
    # noClasses：使用 class 标签，而不是内嵌的内联样式
