baseURL: 'https://blog.duanhjlt.com/'
theme: 'PaperMod'

languageCode: 'zh-cn'
languageName: '简体中文'
hasCJKLanguage: true
title: "CrazyKids's Blog"
paginate: 15
summaryLength: 120 # 文章概览的自字数，默认70

author:
  name: 'duanhongjin'
  email: 'duanhjlt@163.com'
  link: 'https://blog.duanhjlt.com/'

enableInlineShortcodes: true
enableEmoji: true
enableRobotsTXT: true

buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

menu:
  main:
    - weight: 1
      identifier: 'post'
      name: '文章'
      url: '/posts/'
    - weight: 2
      identifier: 'tags'
      name: '标签'
      url: '/tags/'
    - weight: 3
      identifier: 'categories'
      name: '分类'
      url: '/categories/'
    - weight: 4
      identifier: 'about'
      name: '关于'
      url: '/about/'

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  author: duanhongjin
  defaultTheme: auto  # defaultTheme: light or  dark
  disableThemeToggle: false
  DateFormat: "2006-01-02"
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecialistPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideFooter: false # 隐藏页脚
  ShowWordCounts: true
  VisitCount: true
  ShowLastMod: true #显示文章更新时间

  ShowToc: true # 显示目录
  TocOpen: true # 自动展开目录

  extendCodeBackground: false # 代码块是否自动横向展开

  comments: true

  profileMode:
    enable: true
    title: "CrazyKids's Blog"
  
  socialIcons:
    - name: github
      url: "https://github.com/duanhjlt"
    - name: RSS
      url: "index.xml"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/duanhjlt/blog/tree/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

markup:
  highlight:
    noClasses: false