#!/bin/bash

commit="Site update: "$(date)
git add .
git commit -m "$commit"
git push -u origin master

hugo -F --cleanDestinationDir --environment production
sed -i '' '/<meta name="robots" content="noindex">/d' public/index.html
cd public
echo 'blog.crazykids.tech' > CNAME
git add .
git commit -m "$commit"
git push -u origin master
cd ..