#!/bin/bash

commit="Site update: "$(date)
git add .
git commit -m "$commit"
git push -u origin master

hugo -F --cleanDestinationDir
cd public
echo 'blog.duanhjlt.com' > CNAME
git add .
git commit -m "$commit"
git push -u origin master
cd ..